### ISSUE TITLE
Document Namespace Security Network Policy

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#118]
## what
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: foobar
Spec:
  policyTypes:
  - Ingress
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: foobar

```
