### ISSUE TITLE
Document Codefresh Registry Pull Secrets for Clusters 

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#135]
## what
* Describe how to create a pull secret not associated with a user account
## why
* Users should not be exposing their pull secrets

## solutions

1. use dedicated bot account
2. use UI
3. use `cli`

## related
https://codefresh-io.github.io/cli/more/image-pull-secret/
https://hub.docker.com/r/codefresh/cli/tags/
https://docs.cloudposse.com/release-engineering/codefresh/

Or manually...

![image](https://user-images.githubusercontent.com/52489/41517128-85484ec4-726d-11e8-8241-8bdc6810c0f1.png)

```
RunCodefreshCLI:
    title: Running Codefresh CLI ...
    image: 'codefresh/cli:latest'
    commands: 
      - codefresh ...
```
