### ISSUE TITLE
Liveness probe failed: ... server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#161]
## what
* I’m banging my ahead against this: `Liveness probe failed: Get https://100.112.158.75:3000/healthz: http: server gave HTTP response to HTTPS client` trying to deploy the master branch of our app to a new namespace in staging

## why

![image](https://user-images.githubusercontent.com/52489/42190055-073393dc-7e10-11e8-9578-cb62936c219d.png)

Ensure that the `scheme` of the readiness probe matches that of the service.

Also, make sure that the service does not issue a `301` or `302` redirect. That will also cause this error.

**Comment by prashantjain110** [comment]
Hi @osterman ,

Can you please tell me how you have solved this problem as I am also facing this issue.

**Comment by musa11971** [comment]
See below for our fix.

Before:
```yaml
readinessProbe:
  httpGet:
    path: [...]
    port: [...]
```

After:
```yaml
readinessProbe:
  httpGet:
    path: [...]
    port: [...]
    scheme: HTTPS
```
